name: flutter_clean_architecture
description: Flutter Clean Architecture template with BLoC, injectable, Retrofit, and remote localization.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0

  # Dependency injection
  get_it: ^9.2.1
  injectable: ^3.0.0

  # Functional programming
  dartz: ^0.10.1
  equatable: ^2.0.8

  # Networking
  dio: ^5.9.2
  retrofit: ^4.9.2

  # Routing
  go_router: ^17.2.3

  # Localization
  easy_localization: ^3.0.8

  # Local storage
  shared_preferences: ^2.5.5

  # Serialization
  json_annotation: ^4.12.0
  freezed: ^3.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  injectable_generator: ^3.0.2
  json_serializable: ^6.14.0
  retrofit_generator: ^10.2.6

flutter:
  uses-material-design: true
